name: "Puppeteer Screenshot Action"
description: "Run puppeteer script and generate screenshot"
author: "Benjamin Lannon <benjamin@lannonbr.com>"
branding:
  icon: 'camera'
  color: 'green'
runs:
  using: "node12"
  main: "lib/index.js"
inputs:
  url:
    required: true
    description: "The URL you want puppeteer to visit"
  width:
    required: false
    description: "Browser viewport width"
    default: 1920
  height:
    required: false
    description: "Browser viewport height"
    default: 1080
  fullPage:
    required: false
    description: "Controls whether screenshot taken includes entire page"
    default: false
  screenshotName:
    required: false
    description: "The screenshot name if you do not want the default timestamp"
    default: false
